apiVersion: v1
kind: Service
metadata:
  name: demo-web
  labels:
    app: demo
    tier: web
spec:
  type: ClusterIP
  selector:
    app: demo
    tier: web
  ports:
    - name: http
      port: 80
      targetPort: 8080
