// generated by genai_codegen.py (stable header)
output "bucket_name" {
  value       = aws_s3_bucket.bucket.id
  description = "The name of the created S3 bucket"
}

output "bucket_arn" {
  value       = aws_s3_bucket.bucket.arn
  description = "The ARN of the created S3 bucket"
}

output "region" {
  value       = var.region
  description = "The region where the resources were created"
}
