// generated by genai_codegen.py @ 2025-10-17T20:09:09.627044Z
// -------- variables.tf --------
// Inputs kept explicit; no apply-time values.

variable "region" {
  type        = string
  description = "AWS region for the provider."
}

variable "bucket_name" {
  type        = string
  description = "Name of the S3 bucket (must be globally unique)."
}

variable "kms_key_id" {
  type        = string
  description = "KMS key ARN or ID used for SSE-KMS on the bucket."
}

variable "tags" {
  type        = map(string)
  description = "Common tags applied to all resources."
  default     = {}
}

variable "force_destroy" {
  type        = bool
  description = "Set to true to allow terraform to delete the bucket with objects/versions."
  default     = false
}

variable "enable_access_logging" {
  type        = bool
  description = "Enable S3 server access logging to a target bucket/prefix."
  default     = false
}

variable "log_bucket" {
  type        = string
  description = "Target bucket for server access logs (must exist)."
  default     = ""
}

variable "log_prefix" {
  type        = string
  description = "Prefix for access logs in the target bucket."
  default     = "s3-logs/"
}

