// generated by genai_codegen.py (stable header)
variable "kms_key_id" {
  description = "The ARN of the KMS key to use for server-side encryption"
  type        = string
}

variable "region" {
  description = "AWS region where resources will be created"
  type        = string
}

variable "bucket_name" {
  description = "Name of the S3 bucket to create"
  type        = string
}

variable "force_destroy" {
  description = "Enables force destroy for this S3 bucket"
  type        = bool
  default     = false
}

variable "tags" {
  description = "A map of tags to apply to all resources created by this module"
  type        = map(string)
  default     = {}
}
